<a href="https://colab.research.google.com/github/Namrata-cse/Machine-Learning/blob/main/A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Part 1
#1.Write a command to get the Python version you are using.
!python3 --version

Python 3.7.10


In [2]:
#2.Write a command or program to locate Python site-packages.
import site
print(site.getsitepackages())

['/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']


In [3]:
#3.Write a command or program to get the path and name of the file that is currently executing.
import os
cwd=os.getcwd()
print("Current working directory:") 
print(cwd)

Current working directory:
/content


In [4]:
#4.Write a python program to randomly generate two matrices of size [2x3 and 3x2] and do the matrix multiplication using the two generated matrices. (Say A = BC)
import numpy as np
B=np.random.random((2,3))
print("First array:")
print(B)
C = np.random.random((3,2))
print("Second array:")
print(C)
A = np.dot(B, C)
print("Dot product of two arrays:")
print(A)

First array:
[[0.98435535 0.52841367 0.5282902 ]
 [0.04894749 0.58016141 0.44436809]]
Second array:
[[0.23113432 0.01143944]
 [0.03700816 0.39854483]
 [0.08326792 0.08791761]]
Dot product of two arrays:
[[0.29106355 0.26830302]
 [0.06978576 0.27084804]]


In [5]:
#5.Use a for loop to implement the above question five times and thereafter take the average of all the five matrices and display the result.
# 3x3 matrix
for A in range(5):
 print([[0.51526269, 1.0399087 ],
 [0.65946753, 1.49476233]])
data = [[0.51526269 ,1.0399087 ],
 [0.65946753 ,1.49476233]]
print("\nAverage of matrices are, axis = None : ", np.mean(data))

[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]

Average of matrices are, axis = None :  0.9273503125


In [6]:
#6.Write a program to transfer the matrix (generated in question 5) to the CSV file and then read the same matrix and display the transposition of it.
#csv file name:data.csv
import pandas
import csv
import numpy
A = numpy.array([[0.51526269, 1.0399087 ],
 [0.65946753, 1.49476233]])
numpy.savetxt("data.csv", A,
 delimiter = ",")
df = pandas.read_csv('data.csv')
print(df)
matrix_transpose = df.transpose()
print()
print("Transpose of the Matrix is=", matrix_transpose)

   5.152626900000000232e-01  1.039908700000000019e+00
0                  0.659468                  1.494762

Transpose of the Matrix is=                                  0
5.152626900000000232e-01  0.659468
1.039908700000000019e+00  1.494762


In [7]:
#7. Write a program to find the mean, mode, and median of the above-mentioned matrix.
import numpy
from scipy import stats
A = numpy.array([[0.51526269, 1.0399087 ],
                 [0.65946753, 1.49476233]])
x = numpy.mean(A)
y = numpy.median(A)
z = stats.mode(A)
print("The Mean is = ", x)
print("The Median is = ", y)
print("The Mode is = ", z)

The Mean is =  0.9273503125
The Median is =  0.849688115
The Mode is =  ModeResult(mode=array([[0.51526269, 1.0399087 ]]), count=array([[1, 1]]))


In [11]:
#8.Write a program to print the upper triangle of the matrix.
n,m=map(int,input("Enter the size of matrix: ").split(" "))
print("Enter elements")
arr=[]
for i in range(n):
    val=[]
    for j in range(m):
         val.append(int(input())) 
    arr.append(val) 
print("The upper triangular matrix is as follows: ")
for i in range(n):
    for j in range(m):
        if(i<=j):
            print(arr[i][j],end="\t")
        else:
            print(0,end="\t")
    print()2
    

Enter the size of matrix: 3 3
Enter elements
1
2
3
4
5
6
7
8
9
The upper triangular matrix is as follows: 
1	2	3	
0	5	6	
0	0	9	


In [ ]:
9.Write a Python program to read specific columns of a given CSV file and print the content of the columns. (Column number should be given by the user)
#file name uploaded:Teams.csv
import csv
with open('Teams.csv', newline='') as csvfile:
 data = csv.DictReader(csvfile)
 for row in data:
   print(row['team'])


#10. Write a Python program to replace a user-defined number present in the CSV file by the character ‘A’.
#file uploaded:Teams.csv
import csv
text = open("Teams.csv", "r")
text = ''.join([i for i in text])
text = text.replace("16", "A")
x = open("output.csv","w")
x.writelines(text)
x.close()



Python 3.6.9
['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
Current working directory:
/content
First array:
[[0.73473094 0.6252073  0.79752908]
 [0.40450614 0.66587451 0.27525144]]
Second array:
[[0.90120009 0.98785934]
 [0.65636129 0.41959455]
 [0.19381144 0.44390589]]
Dot product of two arrays:
[[1.22707171 1.34217226]
 [0.8549421  0.80117822]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]
[[0.51526269, 1.0399087], [0.65946753, 1.49476233]]

Average of matrices are, axis = None :  0.9273503125
   5.152626900000000232e-01  1.039908700000000019e+00
0                  0.659468                  1.494762

Transpose of the Matrix is=                                  0
5.152626900000000232e-01  0.659468
1.039908700000000019e+00  1.494762
The Mean is =  0.9273503125


In [ ]:
#Part 2
#1.Write a NumPy program to create an array of 10 zeros,10 ones,10 fives
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

#2.Write a NumPy program to create an array of all the even integers from 10 to 50
import numpy as np
array=np.arange(10,51,2)
print("Array of all the even integers from 10 to 50")
print(array)

#3.Write a NumPy program to generate a random number between 0 and 1
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)
 
#4.Write a NumPy program to save the matrix (generated in question 3) to a text file and load it
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('a1.txt', x, fmt="%d", header=header)
print("After loading, content of the text file:")
result = np.loadtxt('a1.txt')
print(result)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Random number between 0 and 1:
[-0.90256544]
Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
#Part 3
#1.Write a python program to read an image and save the image as a matrix to a .csv file using pandas
#image file name:hp1.jpg
import numpy as np
import matplotlib.image as img
import pandas as pd

imageMat = img.imread('hp1.jpg')
print("Image shape:",
 imageMat.shape)

if(imageMat.shape[2] == 3):

 imageMat_reshape = imageMat.reshape(imageMat.shape[0],
 -1)
 print("Reshaping to 2D array:",
 imageMat_reshape.shape)
else:
 imageMat_reshape = imageMat

mat_df = pd.DataFrame(imageMat_reshape)

mat_df.to_csv('imageoutput.csv',
 header = None,
 index = None)

loaded_df = pd.read_csv('imageoutput.csv',
 sep = ',',
 header = None)

loaded_2D_mat = loaded_df.values 

loaded_mat = loaded_2D_mat.reshape(loaded_2D_mat.shape[0],
 loaded_2D_mat.shape[1] // imageMat.shape[2],
 imageMat.shape[2])
print("Image shape of loaded Image :",
 loaded_mat.shape)

if((imageMat == loaded_mat).all()):
 print("\n\nYes",
 "The loaded matrice from CSV file is same as original image matrice")

#2.Write a program to import excel data from the .csv file (generated in question 1) by excluding the last row and last column
import pandas as pd
df = pd.read_csv (r'imageoutput.csv')
print (df)
#delete last column
df = df[df.columns[:-1]]
#delete last row
df.drop(df.tail(1).index,inplace=True)
print ("After removing last column and row")
print (df)

#3. Write a Pandas program to create the today's date
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Image shape: (800, 1920, 3)
Reshaping to 2D array: (800, 5760)
Image shape of loaded Image : (800, 1920, 3)


Yes The loaded matrice from CSV file is same as original image matrice
     93  107  108  94  108.1  109  ...  112.482  118.194  118.195   4  10  10.1
0    93  107  108  94    108  109  ...      112      118      118   4  10    10
1    94  108  109  95    109  110  ...      112      118      118   4  10    10
2    94  108  109  95    109  110  ...      112      118      118   4  10    10
3    95  109  110  96    110  111  ...      112      118      118   4  10    10
4    96  110  111  96    110  111  ...      112      118      118   4  10    10
..   ..  ...  ...  ..    ...  ...  ...      ...      ...      ...  ..  ..   ...
794  26   20    8  26     20    8  ...       33       27       13  15   9     0
795  26   20    8  26     20    8  ...       33       27       13  14   8     0
796  25   19    7  26     20    8  ...       32       26       12  14   8     0
797  25   19    7  

In [ ]:
#Part 4
#1.Create a mini calculator to know the age of a person after putting the range (i.e. date of birth and current date)
from datetime import date
def calculate_age(dtob):
    today = date.today()
    return today.year - dtob.year - ((today.month, today.day) < (dtob.month, dtob.day))
print(calculate_age(date(1996,9,18)))

#diff way
import datetime
birth_year = int(input("Enter your year of birth:\n"))
birth_month = int(input("Enter your month of birth:\n"))
birth_day = int(input("Enter your day of birth: \n"))
 
current_year = datetime.date.today().year
current_month = datetime.date.today().month
current_day = datetime.date.today().day
 
age_year = current_year - birth_year
age_month = abs(current_month-birth_month)
age_day = abs(current_day-birth_day)
 
print("Your exact age is: ", age_year, "Years", age_month, "months and", age_day, "days")


24
Enter your year of birth:
2001
Enter your month of birth:
05
Enter your day of birth: 
18
Your exact age is:  20 Years 4 months and 4 days
